### ISSUE TITLE
How do I set an environment variable before running?

### ISSUE THREAD

**Issue by binarykitchen** [hyPiRion/lein-shell#17]
Hello there

I tried something like this:

```
  :aliases
  {"dev"   ["do" ["shell" "DEV=true"] "run"]}
```

but this didn't work

```
java.io.IOException: Cannot run program "DEV=true"
```

**Comment by hyPiRion** [comment]
Hi there!

It should be possible to do something like that with this setup:

```clj
:aliases {"dev" ["shell" "lein" "run"]}
:shell {:env {"DEV" "true"}}
```

If your main ns is

```clj
(ns my-project.core
  (:gen-class))

(defn -main
  [& args]
  (println (System/getenv "DEV")))
``` 

then `lein dev` will print `true` and `lein run` will print `nil`.

Note that a small shell/bat program which sets up the environment and calls `lein run` should have a smaller startup time. lein-shell isn't really designed to set up environments for `lein run` or other lein tasks.

The documentation also has some information on how to do it. It's located at [Configuration → Environment Variables](https://github.com/hyPiRion/lein-shell/blob/master/doc/DOCUMENTATION.md#environment-variables)

**Comment by binarykitchen** [comment]
Thanks but what if I have other aliases running lein as well and do not want to set `DEV=true` for all of them?

For example:

```
  :aliases
  {"watch" ["shell" "node_modules/.bin/gulp" "watch"]
   "dev"   ["shell" "lein" "run"]
   "test"  ["shell" "node_modules/.bin/gulp" "test"]
   "deps"  ["do" "deps" ["npm" "prune"]]}
```

And only the dev alias should set `DEV=true`, but not the other aliases. How can I do this without adding an external shell/bat program?

**Comment by hyPiRion** [comment]
Right. It's possible to do that by something like this:

```clj
:aliases {"dev" ["shell" "dev" "run"]
          "non-dev" ["shell" "lein" "run"]}
:shell {:commands {"dev" {:default-command "lein"
                          :env {"DEV" "true"}}}}
```

`lein dev` will still print out `true`, but `lein non-dev` will print `nil`.

The subsection [default-command and aliasing](https://github.com/hyPiRion/lein-shell/blob/master/doc/DOCUMENTATION.md#default-command-and-aliasing) in the documentation has some information on what's going on there with the `:commands` and `:default-command` sorcery.

**Comment by binarykitchen** [comment]
Ah, beautiful sorcery. Now all works. Many thanks!

**Comment by hyPiRion** [comment]
No problem! :)
