### ISSUE TITLE
Add ability to run multiple commands in platform substitutions

### ISSUE THREAD

**Issue by danielcompton** [hyPiRion/lein-shell#18]
We have a situation where we need to run multiple shell commands in Windows to achieve the equivalent result in Linus or Mac OS X.

We work around this in other ways, but it would be nice to be able to extend the existing lein shell commands to allow an array of commands like:

```
  :shell {:commands {"open" {:windows ["cmd" "/c" "start"]
                             :macosx  "open"
                             :linux   "xdg-open"}}}
```

Commands can now be strings or arrays of strings, and would be prepended as normal to the array of commands.

Is this approach agreeable to you? If it is I can open a PR to support this syntax.

**Comment by hyPiRion** [comment]
Yeah, this makes sense. It also means it's working more or less exactly like Lein aliases, which is a nice bonus.
