### ISSUE TITLE
Perform parameter expansion in strings

### ISSUE THREAD

**Issue by hyPiRion** [hyPiRion/lein-shell#21]
This library should allow parameter expansions in strings, e.g. `$HOME` would expand to the user's home directory and so forth.

It should also allow you to expand project parameters – e.g. `$:url` should resolve to the project's :url value, and `$[:license :name]` would expand to the licence name.

**Comment by hyPiRion** [comment]
In hindsight, I'm not sure if it's that smart to support environment variable expansion here – it will cause repeatability issue. Perhaps just expanding project parameters is sufficient.

**Comment by hyPiRion** [comment]
@danielcompton guessing you wanted to know that 0.5.0 is released with this functionality. `lein shell cowsay 'We are on version ${:version}'` will print the version you're currently at.

More information is over at https://github.com/hyPiRion/lein-shell/blob/master/doc/DOCUMENTATION.md#parameter-expansion

**Comment by danielcompton** [comment]
Wow thanks! That's incredible.
