### ISSUE TITLE
Invoked shell script cannot access some environment variables

### ISSUE THREAD

**Issue by Ragsboss** [hyPiRion/lein-shell#23]
I'm invoking an existing shell script from my lein project file. This script access environment variable "BUILD_NUMBER" that is not visible in that shell script. The Jenkins job that includes my lein project has a simple echo statement proving the existence of that environment variable with expected value. Any clues?

My alias looks like
`"set-ui-build" ["shell" "./set_ui_build_number.sh"]`

I also tried
`"set-build-version" ["shell" "/bin/sh" "-C" "set-build-version.sh"]`

From the script when I do `printenv` this is all the variables I see.
```+ printenv
LEIN_JVM_OPTS=-XX:+TieredCompilation -XX:TieredStopAtLevel=1
HOSTNAME=9d8dff937413
SHLVL=1
HOME=/home/builder
JVM_OPTS=
LEIN_VERSION=2.6.1
_=/usr/bin/java
LEIN_JAVA_CMD=java
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
CLASSPATH=/home/builder/.lein/self-installs/leiningen-2.6.1-standalone.jar
LEIN_HOME=/home/builder/.lein
TRAMPOLINE_FILE=/tmp/lein-trampoline-0HdJMDu6lxa3x
PWD=/home/builder/helloworld```

**Comment by danielcompton** [comment]
>  This script access environment variable "BUILD_NUMBER" that is not visible in that shell script.

Is that variable [exported](https://help.ubuntu.com/community/EnvironmentVariables#Inheritance)?

**Comment by Ragsboss** [comment]
@danielcompton thank you for your response. This was my bad. I realized our build script was using containers and hence host environment variables are not visible to my script running inside the container..
