### ISSUE TITLE
No more colors when using lein-shell

### ISSUE THREAD

**Issue by binarykitchen** [hyPiRion/lein-shell#25]
There is a command I aliased with your plugin like

```
"test:e2e"  ["shell" "node", "./env/test/js/webdriverio/launcher.js"]
```

which does not print any colors at all.

But when I use it directly like `node ./env/test/js/webdriverio/launcher.js` then I see colors.

**Comment by darwin** [comment]
Directly executed script from your terminal prompt runs in so called TTY mode (colors by default).

Lein-shell invokes scripts in "batch mode" which runs in non-TTY mode (no colors by default). Your node script probably detects this and does not print colors in batch mode which is the right thing to do btw. Usually there is a way how to force/disable colors in either mode, usually via some env variables or command-line options. You should look if your node script supports something like that.

I just tested it on my machine to confirm this behaviour:

```
"x" ["shell" "node" "-p" "-e" "Boolean(process.stdout.isTTY)"]
```

`node -p -e "Boolean(process.stdout.isTTY)"` executed from terminal returns true
`lein x` executed via lein alias above returns false

I double checked this with a simple bash shell script where I detected tty this way:

```bash
#!/bin/bash

if tty -s; then
  echo "is a TTY"
else
  echo "is not a TTY"
fi
```

**Comment by binarykitchen** [comment]
I see, thanks. Can't be fixed within lein-shell then.
