### ISSUE TITLE
Use of platform specific file paths in project.clj

### ISSUE THREAD

**Issue by jneira** [hyPiRion/lein-shell#27]
Hi!, i am trying to support a [`project.clj`](https://github.com/f-f/dhall-clj/blob/6785101d9ec4b2699440a7f856ff940fa9f33d7e/project.clj) that uses the plugin for both *nix and windows. It has a block:
```clojure
:prep-tasks [["shell" "cp" "dhall-lang/standard/dhall.abnf" "resources/"] "javac" "compile"]
```
To support windows i've tried:
```clojure
:prep-tasks [["shell" "cp" "dhall-lang/standard/dhall.abnf" "resources/"] "javac" "compile"]
:shell {:commands {"cp" {:windows ["cmd" "/c" "copy"]}
                              "dhall-lang/standard/dhall.abnf"
                                   {:windows "dhall-lang\\\\standard\\\\dhall.abnf"}
                              "resources/"
                                   {:windows "resources\\\\"}}}
```
But it throws:
```console
The command syntax is not correct
```
Moreover, although it would work, repeating paths could be cumbersome and error prone so i've used a (maybe ugly?) hack:

```clojure
(require '[clojure.java.io :as io])
(defn path [s] (.replace (.getPath (io/file s)) "\\" "\\\\"))
(defproject dhall-clj "0.1.0"	(defproject dhall-clj "0.1.0"
....
  :prep-tasks [["shell" "cp"
                ~(path "dhall-lang/standard/dhall.abnf")
                ~(path "resources/")]
               "javac" "compile"]
   :shell {:commands {"cp" {:windows ["cmd" "/c" "copy"]}}}
```
I wonder if the plugin could be changed to be aware of file path arguments and call `Runtime.exec` with the appropiate platform scpecific ones (maybe with a `{:file path}` or `[:file path1 path2]`  inside `:prep-tasks` vector?)

**Comment by antonmos** [comment]
can this be closed give the merged pr?
